### ISSUE TITLE
您好，请问一下OnDisconnect后应该调用什么方法重连

### ISSUE THREAD

**Issue by RemKeeper** [aynakeya/open-bilibili-live#1]
![image](https://github.com/aynakeya/open-bilibili-live/assets/78486275/1eeb27cf-f957-40e8-b4f9-48f1ec38e0e7)
我尝试了Start和NewOpenBLiveLongConn方法，但是重连好像都没有成功
![image](https://github.com/aynakeya/open-bilibili-live/assets/78486275/f4150086-e93a-41b5-b225-eb0c5ab71767)

![image](https://github.com/aynakeya/open-bilibili-live/assets/78486275/6c267ded-24df-4b74-b6f2-2ea398298a41)
![image](https://github.com/aynakeya/open-bilibili-live/assets/78486275/a0a9d96f-822a-4ba8-9100-d98ef646bd34)

**Comment by aynakeya** [comment]
你好，
先调用CloseConnection确保重置。

然后调用EstablishConnection重连

**Comment by RemKeeper** [comment]
好的，非常感谢
